- the rc.* tags logic applied

diff --git a/.github/workflows/on-tag-prerelease.yml b/.github/workflows/on-tag-prerelease.yml
--- a/.github/workflows/on-tag-prerelease.yml
+++ b/.github/workflows/on-tag-prerelease.yml
@@ -4,6 +4,7 @@ on:
   push:
     tags:
       - '*.*.*'
+      - '*.*.*-rc.*'
 
 jobs:
   version-update:
@@ -23,11 +24,18 @@ jobs:
         shell: bash
         run: |
           tag=${GITHUB_REF/refs\/tags\//}
-          version=${tag#v}
+          if [[ $tag =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "version=${tag}" >> $GITHUB_OUTPUT
+            version=$tag
+          elif [[ $tag =~ ^[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+$ ]]; then
+            echo "version=${tag}" >> $GITHUB_OUTPUT
+            version=$tag
+          else
+            echo "Invalid tag format: $tag"
+            exit 1
+          fi
           branch_prefix=release-
-          echo "tag=$tag" >> $GITHUB_OUTPUT
-          echo "version=$version" >> $GITHUB_OUTPUT
-          echo "branch=$branch_prefix$version" >> $GITHUB_OUTPUT
+          echo "branch=${branch_prefix}${version}" >> $GITHUB_OUTPUT
 
       - name: Run propagate_version.py
         working-directory: ./electron
